name: GitHub-Profile-3D-Contrib
on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          USERNAME: ouzfeya7
      - run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/ouzfeya7/ouzfeya7.git
          git add -A
          git commit -m "Generate 3D contribution graph" || exit 0
          git pull origin main --rebase
          git push
