name: Generate GitHub Stats

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Generate Stats Card (with private contributions)
        uses: anmol098/waka-readme-stats@master
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          WAKATIME_API_KEY: ""
          SHOW_LINES_OF_CODE: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_LANGUAGE: "False"
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
          SHOW_TIMEZONE: "False"
          SHOW_EDITORS: "False"
          SHOW_SHORT_INFO: "False"
          COMMIT_BY_ME: "True"
          COMMIT_MESSAGE: "ci: update stats"
